name: CoreX
version: '${project.version}'
main: org.r7l.corex.CoreX
api-version: '1.21'
author: r7l-labs
description: Custom join and leave messages plugin with cool styling
website: https://github.com/r7l-labs/corex

commands:
  corexreload:
    description: Reloads the CoreX configuration.
    usage: /corexreload
    permission: corex.reload

permissions:
  corex.reload:
    description: Allows reloading the CoreX configuration.
    default: op
